### ISSUE TITLE
Discount code is not applied upon payment

### ISSUE THREAD

**Issue by peterhuppertz** [dualcube/moodle-enrol_stripepayment#57]
The deducted amount is displayed fine once I input the coupon code, but the full price is taken by Stripe upon payment.
<img width="428" alt="image" src="https://user-images.githubusercontent.com/5812004/100608001-1206ed00-330c-11eb-9c18-d09a9c1c3f32.png">

**Comment by peterhuppertz** [comment]
I found the problem in enrol.php. 
`$_SESSION['amount'] = get_stripe_amount($cost, $_SESSION['currency'], false);`
is set in the top. The new amount taking the coupon into account is calculated further down and therefore the new amount is not taking into account. I fixed this simply by moving above code down and set the amount value once the costs are calculated correctly.

**Comment by motifclass** [comment]
Hi peterhuppertz!

That is really cool you figured out the issue. I am having the same problem. I understand your solution up until the point where you move the code down. Do you mind specifying where you move the code down to? I'm new to code so maybe a line number would be helpful? Thank you so very much!

**Comment by ZealJared** [comment]
Cost is saved to session on line 40, then modified on line 126. You can move line 40 to the blank line 129 after the closing curly brace. Refactor should separate logic and presentation. All logic should occur before any presentation.

**Comment by carlosmhpl** [comment]
The modifications suggested at https://github.com/dualcube/moodle-enrol_stripepayment/issues/57 are already included in version 3.2.1 of the module and still not working. The problem is that making the call to validate-coupon.php is as if it did not receive the coupon and returned a 404 error.
![image](https://user-images.githubusercontent.com/76247987/102687546-1aa66100-41f0-11eb-95af-c38c57772a63.png)
![image](https://user-images.githubusercontent.com/76247987/102687559-3578d580-41f0-11eb-8d0d-8f1511b78f39.png)

**Comment by rituparnagithub** [comment]
Hello @carlosmhpl,
We have checked the plugin for the error you mentioned but we couldn't find any such issue.
Below we have attached a video for your reference.

Thank you

https://www.loom.com/share/8c2c75787d67453fabf7963bad6a5d59

**Comment by cirojr** [comment]
@carlosmhpl, have you fixed the problem? I'm having the same message.

**Comment by janeaerlandson** [comment]
I can't determine if the coupon function is going to work for Moodle 3.10. Does anyone know?
